name: Weekly Renovate

on:
  schedule:
    - cron: '0 10 * * 1' # jeden Montag um 10:00 morgens
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Run Renovate
        uses: renovatebot/github-action@v40.1.11
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}